### ISSUE TITLE
flutter gallery bug

### ISSUE THREAD

**Issue by xgqfrms** [flutter/gallery#185] opened 2020-06-18 02:33 UTC
**Describe the bug**

> flutter gallery run bug

![image](https://user-images.githubusercontent.com/7291672/84971101-9dba0200-b14e-11ea-87f6-bab41bbe088c.png)

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

```sh
flutter-gallery flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-CN)
    • Flutter version 1.17.3 at /Users/xgqfrms-mbp/Documents/Flutter/flutter
    • Framework revision b041144f83 (13 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xgqfrms-mbp/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 11 • 00B85F36-BEA7-48CC-B872-F4147A60C283 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

**To Reproduce**

```sh
$ open -a Simulator
$ flutter run
```

<pre style="color: red;">
                                            
Compiler message:
lib/pages/backdrop.dart:163:19: Error: No named parameter with the name 'includeSemantics'.
                  includeSemantics: false,
                  ^^^^^^^^^^^^^^^^
../../Flutter/flutter/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart:38:9: Context: Found this candidate, but the arguments don't match.
  const RawKeyboardListener({
        ^^^^^^^^^^^^^^^^^^^
lib/pages/backdrop.dart:172:17: Error: The method 'ExcludeFocus' isn't defined for the class '_BackdropState'.
 - '_BackdropState' is from 'package:gallery/pages/backdrop.dart' ('lib/pages/backdrop.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ExcludeFocus'.
              : ExcludeFocus(child: _settingsPage),
</pre>

**Comment by guidezpl** [comment] 2020-06-18 07:50
Duplicate of #182

**Closed by guidezpl** 2020-06-18 07:50 UTC
Labels: bug

**Comment by xgqfrms** [comment] 2020-06-19 15:31
# `master` branch new feature bug

```sh
# checkout master
$ git checkout master

$ 

```

https://github.com/flutter/gallery/issues/152

***

# ⚠️❌🕵️‍♂️

> but I  was download a `.zip` file, which not exist git branch at all!

**Comment by xgqfrms** [comment] 2020-06-19 15:35
> Duplicate of #182

Please change the duplicate issue reference to #152, for more fast find the really solution.
