### ISSUE TITLE
Error Build failed

### ISSUE THREAD

**Issue by assang** [flutter/gallery#215] opened 2020-07-17 12:21 UTC
Launching lib\main.dart on Lenovo K8 Plus in debug mode...

Compiler message:
lib/main.dart:16:57: Error: Unexpected token ';'.
import 'package:gallery/themes/gallery_theme_data.dart';;
                                                        ^
Running Gradle task 'assembleDebug'...
lib/pages/backdrop.dart:163:19: Error: No named parameter with the name 'includeSemantics'.
                  includeSemantics: false,
                  ^^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart:38:9: Context: Found this candidate, but the arguments don't match.
  const RawKeyboardListener({
        ^^^^^^^^^^^^^^^^^^^
lib/pages/backdrop.dart:172:17: Error: The method 'ExcludeFocus' isn't defined for the class '_BackdropState'.
 - '_BackdropState' is from 'package:gallery/pages/backdrop.dart' ('lib/pages/backdrop.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ExcludeFocus'.
              : ExcludeFocus(child: _settingsPage),
                ^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:225:21: Error: The getter 'FilteringTextInputFormatter' isn't defined for the class 'TextFormFieldDemoState'.
 - 'TextFormFieldDemoState' is from 'package:gallery/demos/material/text_field_demo.dart' ('lib/demos/material/text_field_demo.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FilteringTextInputFormatter'.
                    FilteringTextInputFormatter.digitsOnly,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/studies/crane/backlayer.dart:38:11: Error: The method 'ExcludeFocus' isn't defined for the class '_BackLayerState'.
 - '_BackLayerState' is from 'package:gallery/studies/crane/backlayer.dart' ('lib/studies/crane/backlayer.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ExcludeFocus'.
          ExcludeFocus(
          ^^^^^^^^^^^^

Compiler message:
lib/main.dart:16:57: Error: Unexpected token ';'.
import 'package:gallery/themes/gallery_theme_data.dart';;
                                                        ^
lib/pages/backdrop.dart:163:19: Error: No named parameter with the name 'includeSemantics'.
                  includeSemantics: false,
                  ^^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart:38:9: Context: Found this candidate, but the arguments don't match.
  const RawKeyboardListener({
        ^^^^^^^^^^^^^^^^^^^
lib/pages/backdrop.dart:172:17: Error: The method 'ExcludeFocus' isn't defined for the class '_BackdropState'.
 - '_BackdropState' is from 'package:gallery/pages/backdrop.dart' ('lib/pages/backdrop.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ExcludeFocus'.
              : ExcludeFocus(child: _settingsPage),
                ^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:225:21: Error: The getter 'FilteringTextInputFormatter' isn't defined for the class 'TextFormFieldDemoState'.
 - 'TextFormFieldDemoState' is from 'package:gallery/demos/material/text_field_demo.dart' ('lib/demos/material/text_field_demo.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FilteringTextInputFormatter'.
                    FilteringTextInputFormatter.digitsOnly,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/studies/crane/backlayer.dart:38:11: Error: The method 'ExcludeFocus' isn't defined for the class '_BackLayerState'.
 - '_BackLayerState' is from 'package:gallery/studies/crane/backlayer.dart' ('lib/studies/crane/backlayer.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ExcludeFocus'.
          ExcludeFocus(
          ^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by guidezpl** [comment] 2020-07-17 12:23
Please read the README :) Duplicate of #152

**Closed by guidezpl** 2020-07-17 12:23 UTC
