### ISSUE TITLE
App not launching in Android Flutter 3.10

### ISSUE THREAD

**Issue by ssantosb** [flutter/gallery#953] opened 2023-05-27 23:32 UTC
### Existing issue?

- [X] I checked the [existing issues](https://github.com/flutter/gallery/issues)

## Expected vs actual result:

I cloned the repo to try to run it on an Android device. I expected to run the app locally. First, I executed:
`flutter pub get`
`flutter pub upgrade`
to update libraries and get ready to launch the project. However, after executing `flutter run`, it failed to launch with the following error: 

`Exception: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running flutter create -t app<app-directory> and then move the dart code, assets and pubspec.yaml to the new project`

I tried doing what the prompt says: creating another project and moving the code to that one. However, it still doesn't work. Running `flutter clean` doesn't seem to fix it out. I also ran `flutter doctor` to check if something was wrong and it doesn't seem like anything's wrong.

## Steps to reproduce:
1. Upgrade `Flutter  3.10`
2. Clone the repo
3. Try to run it in Android

## Issues related

Some weeks ago someone already pointed out this problem in #950 but that issues was closed after #948 made a pull request with changes to fix it for macOs. Unfortunately, those changes don't fix it for Android. 

### Relevant log output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Versi¢n 10.0.22621.1702], locale
    es-CO)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.10.4)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.57.0)
[√] VS Code, 64-bit edition (version 1.76.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

**Comment by guidezpl** [comment] 2023-06-03 09:45
This app requires `flutter master channel`, and as I'm unable to reproduce locally on an emulator nor a physical device, I'll close this issue. Please reopen if you still run into issues.

**Comment by chenmrU** [comment] 2023-06-08 08:40
I have encountered the same problem as well.

**Comment by zhangi** [comment] 2023-06-20 04:18
same issue here
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.1 22C65 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.79.0)
[✓] Connected device (3 available)
[✓] Network resources
$ git rev-parse HEAD
d77920b4ced4a105ad35659fbe3958800d418fb9

**Comment by guidezpl** [comment] 2023-06-20 08:39
There are a few things to fix
`git pull` in the gallery repo to update to the latest. `flutter channel master` and `flutter upgrade` to use the master channel, and follow the listed steps for Xcode

**Comment by ChenSino** [comment] 2023-07-26 08:05
same problem：
```shell
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on Manjaro Linux 6.4.3-1-MANJARO, locale zh_CN.UTF-8)
    • Flutter version 3.10.6 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (13 天前), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/chenkun/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at:
      /home/chenkun/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.3)
    • Android Studio at
      /home/chenkun/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996
    • Flutter plugin version 74.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at
      /home/chenkun/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /home/chenkun/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-1/231.9392.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • RNA AN00 (mobile) • adb-AVYYUT1910008906-ETAnA7._adb-tls-connect._tcp • android-arm64  • Android 12 (API 31)
    • Linux (desktop)   • linux                                             • linux-x64      • Manjaro Linux
      6.4.3-1-MANJARO
    • Chrome (web)      • chrome                                            • web-javascript • Google Chrome
      115.0.5790.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
```shell
$ git rev-parse HEAD
873b7054da3ae56f099df92405eed4fc406498af
```

**Comment by guidezpl** [comment] 2023-07-26 08:34
`Flutter (Channel stable`

Please see https://github.com/flutter/gallery/issues/953#issuecomment-1598358677

**Comment by Agoni1** [comment] 2023-08-07 09:03
> There are a few things to fix `git pull` in the gallery repo to update to the latest. `flutter channel master` and `flutter upgrade` to use the master channel, and follow the listed steps for Xcode

great!

**Closed** 2023-08-09 11:49 UTC
Labels: bug, waiting for developer response
