### ISSUE TITLE
Flutter gallery v2.10.2 fails to start on embedded Linux

### ISSUE THREAD

**Issue by aduskett** [flutter/gallery#994] opened 2023-08-17 17:25 UTC
### Existing issue?

- [X] I checked the [existing issues](https://github.com/flutter/gallery/issues)

## Expected vs actual result:
Expected: The Flutter gallery application should start

Actual results: `Unhandled Exception: MissingPluginException(No implementation found for method getApplicataionDocumentsDirectory on channel plugins.flutter.io/path_provider`

## Steps to reproduce:
`git clone https://gitlab.com/aduskett/buildroot-flutter.git -b flutter-gallery-2.10.2 && cd buildroot-flutter && make flutter_x86_64_efi_demo_defconfig && make -Otarget -j$(nproc) && sh ./board/flutter_x86_64/run-qemu`

Flutter-gallery should start up automatically but does not.
Revision 6a8d738c94d0710e229d726729c09fdb5ccaf7ed works properly and is what the [meta-flutter](https://github.com/meta-flutter/meta-flutter/blob/kirkstone/recipes-graphics/flutter-apps/flutter-gallery_git.bb)
repository is using.

**Comment by aduskett** [comment] 2023-08-17 18:13
I dug into the problem a bit further. 287b20a8bfc71196cd733625e622b98b2f84bef1 is the commit that causes the above error. I am not sure where in that commit is the problem.

**Comment by aduskett** [comment] 2023-08-17 18:45
One more comment: It looks like the get_storage package is the culprit. If I remove `await GetStorage.init();` from main.dart, the application starts.

**Comment by parlough** [comment] 2024-01-13 05:05
Thanks for opening the issue and looking into the cause! I'm going to close this issue in favor of https://github.com/flutter/gallery/issues/979 which [discusses](https://github.com/flutter/gallery/issues/979#issuecomment-1693361972) the solution in more detail. Thanks again :)

**Closed by parlough** 2024-01-13 05:05 UTC
Labels: bug, triage
