### ISSUE TITLE
Material3! Material3! Material3!

### ISSUE THREAD

**Issue by SteveCruise** [flutter/gallery#927] opened 2023-04-13 06:58 UTC
### Description

support Material3, use Material3, just Material3!
```dart
theme: ThemeData(
  useMaterial3 : true,
  colorSchemeSeed : themeState.theme,
),
darkTheme: ThemeData(
  useMaterial3 : true,
  colorSchemeSeed : themeState.theme,
  brightness: Brightness.dark,
),
```

**Comment by guidezpl** [comment] 2023-04-13 08:37
Haha thanks for the enthusiasm, closing as duplicate of https://github.com/flutter/gallery/issues/629

**Closed by guidezpl** 2023-04-13 08:37 UTC
Labels: enhancement, triage
