### ISSUE TITLE
Can run app

### ISSUE THREAD

**Issue by neketsushonen** [flutter/gallery#948] opened 2023-05-07 22:57 UTC
### Existing issue?

- [X] I checked the [existing issues](https://github.com/flutter/gallery/issues)

### What happened?

Hello, when I execute the command `fflutter run -d 2c19bbe87d0d7ece lib/main.dart `, I got the following exception:
`
* What went wrong:
Plugin [id: 'dev.flutter.flutter-gradle-plugin', version: '1.0.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'dev.flutter.flutter-gradle-plugin:dev.flutter.flutter-gradle-plugin.gradle.plugin:1.0.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
`
I had to remove  `id "dev.flutter.flutter-gradle-plugin"` from android/app/build.gradle to got it compiling successfully. ¿Did I have doing right?

### Relevant log output

```shell
[✓] Flutter (Channel beta, 3.10.0-1.5.pre, on macOS 13.3.1 22E772610a darwin-arm64, locale en-CL)
    • Flutter version 3.10.0-1.5.pre on channel beta at /Users/chunhaulai/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b1c77b7ed3 (hace 5 días), 2023-05-02 21:11:36 -0600
    • Engine revision 50e509c2bd
    • Dart version 3.0.0 (build 3.0.0-417.4.beta)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/chunhaulai/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/chunhaulai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • SM A920F (mobile) • 2c19bbe87d0d7ece • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by guidezpl** [comment] 2023-06-03 09:51
Related to https://github.com/flutter/flutter/issues/125009, please update the Android Studio Flutter plugin, `flutter channel master` and reopen this issue if you're still facing this issue. I'll close it because I'm unable to reproduce with everything updated to latest versions.

**Closed by guidezpl** 2023-06-03 09:51 UTC
Labels: bug, triage

**Comment by Akarshit7** [comment] 2023-08-26 19:16
I am having the same issue 
How to resolve it
