### ISSUE TITLE
Problems in Windows version

### ISSUE THREAD

**Issue by wnstngs** [flutter/gallery#697] opened 2022-05-24 10:28 UTC
* System text scaling:
    <details>
    <summary>
    Text looks too wide
    </summary>
    
     ![image](https://user-images.githubusercontent.com/64602598/170011147-cd8071bc-8d0c-4771-9ff3-56127ae08c42.png)
    
    ![image](https://user-images.githubusercontent.com/64602598/170010965-efe9f23f-aaf1-4419-aa3f-4bb11cf85509.png)

    </details>

* In all scrolling widgets the mouse wheel scrolling is very slow

* Scrolling scrollbar on main page does not work (but works in categories lists)

* The slider only works if you move it with thumb, but it does not work if you press the scrollbar itself.

**Comment by faizanMayo786** [comment] 2022-05-27 15:40
Yes i had the same issue

**Comment by guidezpl** [comment] 2022-05-30 15:15
cc @Piinks I confirmed these issues on Windows, any clues?

**Comment by Piinks** [comment] 2022-06-06 23:20
Looking at https://gallery.flutter.dev/#/ today, I do not see a scrollbar on the main page, so I am not sure.

**Comment by wnstngs** [comment] 2022-06-07 11:07
> Looking at https://gallery.flutter.dev/#/ today, I do not see a scrollbar on the main page, so I am not sure.

On the right side:
![image](https://user-images.githubusercontent.com/64602598/172365062-251de6a3-734b-449e-b85c-a91fad1f2cc8.png)

**Comment by Piinks** [comment] 2022-06-07 14:36
You may be looking at an older version of the gallery. I think it was removed in https://github.com/flutter/gallery/pull/524
I do not have a windows machine to check this on, but on Mac and iOS there is no scrollbar there in the currently deployed version.

**Comment by wnstngs** [comment] 2022-06-07 16:16
> You may be looking at an older version of the gallery. I think it was removed in #524 I do not have a windows machine to check this on, but on Mac and iOS there is no scrollbar there in the currently deployed version.

It is v2.9.2

**Comment by Piinks** [comment] 2022-06-07 16:40
Ah! That must be it then. I am seeing the latest version v2.9.3. It looks like this issues is resolved with the latest version.

**Comment by guidezpl** [comment] 2023-01-13 14:44
Closing as this is against an old version. If this is still occurring at HEAD, please file a new issue

**Closed by guidezpl** 2023-01-13 14:44 UTC
Labels: bug
