### ISSUE TITLE
The method 'ExcludeFocus' isn't defined for the type '_BackLayerState'

### ISSUE THREAD

**Issue by RaulMarquezInclan** [flutter/gallery#182] opened 2020-06-13 03:11 UTC
Getting the error:

`The method 'ExcludeFocus' isn't defined for the type '_BackLayerState'`

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.1 at C:\SDK\FlutterSDK\flutter
    • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\y_cha\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\y_cha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

I just downloaded the code to my windows machine, opened it in VS Code, after downloading packages and analyzing it shows the error above in the backlayer.dart file:

```
  @override
  Widget build(BuildContext context) {
    final tabIndex = widget.tabController.index;
    return IndexedStack(
      index: tabIndex,
      children: [
        for (BackLayerItem backLayerItem in widget.backLayerItems)
          **ExcludeFocus**( // <--- Error here
            excluding: backLayerItem.index != tabIndex,
            child: backLayerItem,
          )
      ],
    );
  }
```

How can I fix this?

**Comment by guidezpl** [comment] 2020-06-15 10:53
Duplicate of #152

**Closed by guidezpl** 2020-06-15 10:53 UTC
Labels: bug
