### ISSUE TITLE
Manjaro Linux Fonts Is Square

### ISSUE THREAD

**Issue by ilovesusu** [flutter/gallery#540] opened 2021-09-07 09:39 UTC
OS:Manjaro Linux
Releases :Flutter Gallery v2.9.2
![2021-09-07_17-39](https://user-images.githubusercontent.com/12681726/132322716-f6c46ef3-c1a9-4c5f-8921-f07b9e7d973c.png)

**Comment by guidezpl** [comment] 2021-09-07 09:46
Can you please provide the output of `flutter doctor -v`? Also, if you open the settings in the upper right, which locale is selected?

**Comment by ilovesusu** [comment] 2021-09-11 04:19
![1234578](https://user-images.githubusercontent.com/12681726/132935979-a8ba387c-48a2-4297-9d3c-1f346cf9c9e5.png)

**Comment by guidezpl** [comment] 2021-09-14 11:52
`zh_CN` is a locale supported by the gallery, but yours is `zh_UTF-8_CN`. Hence all translantable strings are not rendered correctly. @HansMuller Do you know who might be best able to help with this issue?

**Comment by ilovesusu** [comment] 2021-11-04 11:18
Maybe I did not install fonts? ! But I don’t know what font is needed
It is also possible that the font currently in use does not support Chinese? !

**Comment by guidezpl** [comment] 2021-11-04 11:30
<img width="1166" alt="Screen Shot 2021-11-04 at 12 28 14" src="https://user-images.githubusercontent.com/6655696/140306031-fea243ba-10ac-4d51-a190-0bf33ad24bf6.png">

The font is supported (this is on web), so this might be a Linux issue. The best thing to do would be to create a simple reproducible sample `flutter create` and create a bug on https://github.com/flutter/flutter

**Comment by guidezpl** [comment] 2021-12-09 08:29
This might be fixed by #556. If not, please reopen

**Closed by guidezpl** 2021-12-09 08:29 UTC
Labels: bug

**Comment by ilovesusu** [comment] 2021-12-09 13:33
no it don't work for me

**Comment by guidezpl** [comment] 2021-12-09 20:25
I'm unable to reproduce on Linux as well. But if you have reproduction steps, like a small code sample, please let me know of open an issue in the flutter/flutter repo
