### ISSUE TITLE
[Web] Bug UI Picker 

### ISSUE THREAD

**Issue by andgar2010** [flutter/gallery#818] opened 2022-10-28 19:50 UTC
Bug UI Picker on Web
![image](https://user-images.githubusercontent.com/19521054/198720533-5c91b110-238d-4651-a73d-c8809fb45f97.png)

Windows 11
Edge 106
1920x1080

**Comment by guidezpl** [comment] 2022-10-31 21:58
Closing as duplicate of #384

**Closed by guidezpl** 2022-10-31 21:58 UTC
