### ISSUE TITLE
localizations doesn't work

### ISSUE THREAD

**Issue by upcwangying** [flutter/gallery#132] opened 2020-04-29 03:29 UTC
**Is your feature request related to a problem? Please describe.**
I want to enable localization in my APP, and this [gallery repo](https://github.com/flutter/gallery/tree/v2.3) inspired me.  But localizations doesn't work.
[my repo](https://github.com/upcwangying/l10n_bug).

**Describe the solution you'd like**
How to make localization work?

**Describe alternatives you've considered**
The `flutter_i18n` package does not meet my requirements.

**Comment by guidezpl** [comment] 2020-04-29 11:03
Hi, can you please provide more context? What doesn't work, what were you trying to do, can you provide a link to code, etc.?

**Comment by upcwangying** [comment] 2020-04-29 11:21
https://github.com/upcwangying/l10n_bug

**Comment by guidezpl** [comment] 2020-04-29 12:31
Hmm, interesting. Even when I specified  `locale: Locale('zh'),` on `MaterialApp`, it still used the English string. @shihaohong do you have an idea?

**Comment by shihaohong** [comment] 2020-04-29 17:40
Hi @upcwangying, thank you for your question. The reason that it's not working is that some of the steps of the `intl` library's l10n process weren't followed correctly. I [created a PR](https://github.com/upcwangying/l10n_bug/pull/1) with instructions on how to get your application working correctly.

However, I also want to point out that the gallery uses an internationalization workflow that is new and not related to the `intl` workflow you're currently using. If you're curious on how the code works for the new process, see `flutter/dev/tools/localization/bin/gen_l10n.dart` in the Flutter source code. Once the new gen_l10n workflow is released, there'll be a user guide on how to use the new process.

**Comment by shihaohong** [comment] 2020-04-29 17:40
If you have further questions about how any of this works, please feel free to comment on the PR I opened. I'll close this issue since it's not a bug with Flutter or the Flutter gallery.

**Closed by shihaohong** 2020-04-29 17:40 UTC
Labels: enhancement
