### ISSUE TITLE
[Reply] Mobile FAB uses SizedBox instead of FAB

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/gallery#281] opened 2020-08-31 21:01 UTC
**Describe the bug**
Because of an a11y issue with the animations package, we use a `SizedBox` instead of a fab. A `SizedBox` does not retain the visual states of a `FAB` so this is a workaround until this issue is fixed in the animations package.

To switch channel run:
```bash
flutter channel master
flutter upgrade
```

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

```
```

**To Reproduce**

**Expected behavior**
A floating action button works as the returned widget in `OpenContainer`  `closedBuilder` property.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cmhokej** [comment] 2020-09-20 19:25
#130

**Comment by cmhokej** [comment] 2020-09-20 19:25
Duplicate of #

**Closed** 2021-12-09 08:58 UTC
Labels: bug, study, P3, a11y
